apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: voteapp-deploy
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/aayanshahirwar/k8s-kind-voting-app.git
    targetRevision: HEAD
    path: k8s-specifications
  destination: 
    server: https://kubernetes.default.svc
    namespace: voteapp

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
