apiVersion: v1
kind: Service
metadata:
  labels:
    app: result
  name: result
  namespace: voteapp
spec:
  type: NodePort
  selector:
    app: result
  ports:
    - name: "http"
      port: 80         # Accessible from within the cluster
      targetPort: 80   # Target the container’s port
      nodePort: 31001  # Accessible externally (via NodePort)
